from .token import TokenType

KEYWORD_DICT = {
    "VAR": TokenType.VAR,
    "LOAD": TokenType.LOAD,
    "SET": TokenType.SET,

    # "MOVE": TokenType.MOVE,
    "ADD": TokenType.ADD,
    # "SUB": TokenType.SUB,
    # "MUL": TokenType.MUL,
    # "DIV": TokenType.DIV,
    # "INC": TokenType.INC,
    # "DEC": TokenType.DEC,
    # "AND": TokenType.AND,
    # "OR": TokenType.OR,
    # "XOR": TokenType.XOR,
    # "NOT": TokenType.NOT,
    # "SHL": TokenType.SHL,
    # "SHR": TokenType.SHR,
    # "CMP": TokenType.CMP,
    # "JMP": TokenType.JMP,
    # "JE": TokenType.JE,
    # "JNE": TokenType.JNE,
    # "JG": TokenType.JG,
    # "JL": TokenType.JL,
    # "JGE": TokenType.JGE,
    # "JLE": TokenType.JLE,
    # "FUNC": TokenType.FUNC,
    # "ENDFUNC": TokenType.ENDFUNC,
    # "CALL": TokenType.CALL,
    # "RET": TokenType.RET,
    # "LOOP": TokenType.LOOP,
    # "ENDLOOP": TokenType.ENDLOOP,
    # "WHILE": TokenType.WHILE,
    # "ENDWHILE": TokenType.ENDWHILE,
    # "FOR": TokenType.FOR,
    # "ENDFOR": TokenType.ENDFOR,
    # "FROM": TokenType.FROM,
    # "TO": TokenType.TO,
    # "STEP": TokenType.STEP,
    # "REPEAT": TokenType.REPEAT,
    # "UNTIL": TokenType.UNTIL,
    # "IF": TokenType.IF,
    # "ELSE": TokenType.ELSE,
    # "ENDIF": TokenType.ENDIF,
    # "PUSH": TokenType.PUSH,
    # "POP": TokenType.POP,

    "PRINT": TokenType.PRINT,
    "INPUT": TokenType.INPUT,
    "HALT": TokenType.HALT,
    "NOP": TokenType.NOP,
}